apiVersion: v1
kind: Service
metadata:
  name: html-lb
  labels:
    app: html-lb
spec:
  ports:
    - port: 80
  selector:
    app: html-deploy
    tier: frontend
  type: LoadBalancer
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: html-deploy
  labels:
    app: html-deploy
spec:
  selector:
    matchLabels:
      app: html-deploy
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: html-deploy
        tier: frontend
    spec:
      containers:
      - image: abhijeetdebe/htmlimage:1
        name: html-deploy
        ports:
        - containerPort: 80
          name: html-deploy
        volumeMounts:
        - name: html-pvc
          mountPath: /var/www/html
      volumes:
      - name: html-pvc
        persistentVolumeClaim:
          claimName: efs-pvc
