apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: clusterEks
  region: ap-south-1

nodeGroups:
   - name: nodegroup-1
     desiredCapacity: 2
     instanceType: t2.micro
     ssh:
        publicKeyName: eks-key
   - name: nodegroup-2
     desiredCapacity: 1
     instanceType: t2.small
     ssh:
        publicKeyName: eks-key
