kind: Deployment
apiVersion: apps/v1
metadata:
  name: efs-pro
spec:
  selector:
    matchLabels:
      app: efs-pro
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: efs-pro
    spec:
      containers:
        - name: efs-pro
          image: quay.io/external_storage/efs-provisioner:v0.1.0
          env:
            - name: FILE_SYSTEM_ID
              value: fs-c2e66d13
            - name: AWS_REGION
              value: ap-south-1
            - name: PROVISIONER_NAME
              value: eks-pro/aws-efs
          volumeMounts:
            - name: pv-volume
              mountPath: /persistentvolumes
      volumes:
        - name: pv-volume
          nfs:
            server: fs-c2e66d13.efs.ap-south-1.amazonaws.com
            path: /