apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: rbac
subjects:
  - kind: ServiceAccount
    name: myns
    namespace: myns
roleRef:
  kind: ClusterRole
  name: clusterEks
  apiGroup: rbac.authorization.k8s.io
